#!/usr/bin/env python3
"""Verify complete generated output against canonical content and semantics."""
from __future__ import annotations

import json
from pathlib import Path

from generate_lockfile import _file_records, build_lockfile
from generate_registry import build_registry
from refresh_skill_collections import _bundle_targets, expected_metadata
from skill_lib import skill_collections

ROOT = Path(__file__).resolve().parents[1]
BUILD_DIR = ROOT / "distributions"
MARKER_TEXT = "generated by scripts/refresh_skill_collections.py\n"


def _plain_file(path: Path, root: Path, errors: list[str]) -> bool:
    for entry in (path, *path.parents):
        if entry == root:
            break
        if entry.is_symlink():
            errors.append(f"{path}: symlink in generated file path")
            return False
    if not path.is_file():
        errors.append(f"{path}: missing generated file")
        return False
    return True


def _compare_json(path: Path, expected: dict, root: Path, errors: list[str]) -> None:
    if not _plain_file(path, root, errors):
        return
    try:
        actual = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        errors.append(f"{path}: invalid JSON ({exc})")
        return
    if actual != expected:
        errors.append(f"{path}: does not match canonical source semantics or content hashes")
    if path.stat().st_mode & 0o111:
        errors.append(f"{path}: generated metadata must not be executable")


def validate_generated(root: Path) -> list[str]:
    errors: list[str] = []
    try:
        collections = skill_collections(root)
        metadata = expected_metadata(root)
        registry = build_registry(root)
        lock = build_lockfile(root)
        targets = _bundle_targets(root)
    except (OSError, ValueError, TypeError) as exc:
        return [f"Unable to derive expected output from canonical source: {exc}"]

    _compare_json(root / "distributions" / "skills-registry.json", registry, root, errors)
    _compare_json(root / "distributions" / "skills-lock.json", lock, root, errors)
    expected_files = {
        "distributions/skills-registry.json",
        "distributions/skills-lock.json",
    }
    for relative, expected in metadata.items():
        path = root / relative
        if relative.startswith("distributions/"):
            expected_files.add(relative)
        if not _plain_file(path, root, errors):
            continue
        try:
            if relative.endswith(".json"):
                if json.loads(path.read_text(encoding="utf-8")) != json.loads(expected):
                    errors.append(f"{path}: descriptor differs from canonical source")
            elif path.read_text(encoding="utf-8") != expected:
                errors.append(f"{path}: generated content differs from canonical source")
            if path.stat().st_mode & 0o111:
                errors.append(f"{path}: generated metadata must not be executable")
        except (OSError, ValueError) as exc:
            errors.append(f"{path}: unreadable or invalid metadata ({exc})")

    locked_by_path = {entry["path"]: entry for entry in lock["skills"]}
    names = {path.name for path in collections["example"]}
    for target in targets:
        if target.is_symlink() or not target.is_dir():
            errors.append(f"{target}: missing real bundle directory")
            continue
        marker = target / ".skills-generated"
        expected_files.add(marker.relative_to(root).as_posix())
        if _plain_file(marker, root, errors):
            if marker.read_text(encoding="utf-8") != MARKER_TEXT:
                errors.append(f"{marker}: invalid generated marker")
            if marker.stat().st_mode & 0o111:
                errors.append(f"{marker}: generated marker must not be executable")
        actual_names = {entry.name for entry in target.iterdir()} - {".skills-generated"}
        if actual_names != names:
            errors.append(f"{target}: missing {sorted(names - actual_names)}, extra {sorted(actual_names - names)}")
        for source in collections["example"]:
            source_path = source.relative_to(root).as_posix()
            expected_records = locked_by_path[source_path]["files"]
            destination = target / source.name
            for record in expected_records:
                expected_files.add((destination / record["path"]).relative_to(root).as_posix())
            try:
                actual_records = _file_records(destination)
                if actual_records != expected_records:
                    errors.append(f"{destination}: full folder content or executable mode differs from {source_path}")
            except (OSError, ValueError) as exc:
                errors.append(f"{destination}: {exc}")

    build_dir = root / "distributions"
    actual_files: set[str] = set()
    if build_dir.is_symlink() or not build_dir.is_dir():
        errors.append(f"{build_dir}: missing real distributions directory")
    else:
        for path in build_dir.rglob("*"):
            if path.is_symlink():
                errors.append(f"{path}: generated output contains a symlink")
            elif path.is_file():
                actual_files.add(path.relative_to(root).as_posix())
            elif not path.is_dir():
                errors.append(f"{path}: generated output contains a non-regular file")
        missing, extra = expected_files - actual_files, actual_files - expected_files
        if missing:
            errors.append(f"Missing generated files: {sorted(missing)}")
        if extra:
            errors.append(f"Unexpected generated files: {sorted(extra)}")
    return errors


def main() -> int:
    errors = validate_generated(ROOT)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print("Generated runtime output matches all canonical skills, plugin packages, metadata, and modes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
